-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, CONCAT(UGU.CITY, " ", UGU.STREET_ADDRESS1, " ", UGU.STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(UGU.TLNO,3), '-', MID(UGU.TLNO,4,4), '-', RIGHT(UGU.TLNO, 4)) AS 전화번호
FROM (SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3) AS UGB JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
ORDER BY UGU.USER_ID DESC