-- 코드를 입력하세요
# 2022년 4월 13일 취소되지 않은 흉부와과(cs) 진료 예약 내역
SELECT AP.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM (APPOINTMENT AS AP JOIN DOCTOR AS D ON AP.MDDR_ID = D.DR_ID) JOIN PATIENT AS P ON AP.PT_NO = P.PT_NO
WHERE DATE_FORMAT(AP.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND AP.MCDP_CD = 'CS' AND AP.APNT_CNCL_YN = 'N'
ORDER BY AP.APNT_YMD