-- 코드를 입력하세요
SELECT DISTINCT(CRCC.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '세단' AND CRCRH.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CRCC.CAR_ID DESC