-- 코드를 입력하세요
SELECT FP.CATEGORY, MFP.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP JOIN (
    SELECT PRODUCT_ID, CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) AS MFP ON FP.CATEGORY = MFP.CATEGORY AND FP.PRICE = MFP.MAX_PRICE
ORDER BY MFP.MAX_PRICE DESC